[
{
  "name": "Sax & Fön",
  "adress": "Rådmansgatan 46",
  "zip": "113 57 Stockholm",
  "time": "12:00",
  "tel": "08-522 389 20",
  "site": "www.salongweb.se",
  "rating": "(32)",
  "price": "320 kr",
  "timeEst": "30 min",
  "open": "Öppet till 19.00 idag",
  "desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris"
},
{
  "name" : "Scissorfingers",
  "adress" : "Rådmansgatan 46",
  "zip" : "113 57 Stockholm",
  "time" : "12:00",
  "tel" : "08-522 389 20",
  "site" : "www.salongweb.se",
  "rating" : "(32)",
  "price" : "520 kr",
  "timeEst" : "30 min",
  "open" : "Öppet till 19.00 idag",
  "desc" : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris"},
{
  "name" : "Hårman",
  "adress" : "Rådmansgatan 46",
  "zip" : "113 57 Stockholm",
  "time" : "12:00",
  "tel" : "08-522 389 20",
  "site" : "www.salongweb.se",
  "rating" : "(32)",
  "price" : "150 kr",
  "timeEst" : "30 min",
  "open" : "Öppet till 19.00 idag",
  "desc" : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris"
},
{
  "name" : "HairTeam",
  "adress" : "Rådmansgatan 46",
  "zip" : "113 57 Stockholm",
  "time" : "12:00",
  "tel" : "08-522 389 20",
  "site" : "www.salongweb.se",
  "rating" : "(32)",
  "price" : "120 kr",
  "timeEst" : "30 min",
  "open" : "Öppet till 19.00 idag",
  "desc" : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris"
},
{
  "name" : "Hårstudio",
  "adress" : "Rådmansgatan 46",
  "zip" : "113 57 Stockholm",
  "time" : "12:00",
  "tel" : "08-522 389 20",
  "site" : "www.salongweb.se",
  "rating" : "(32)",
  "price" : "220 kr",
  "timeEst" : "30 min",
  "open" : "Öppet till 19.00 idag",
  "desc" : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris"
}]
